default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: tracking_app
  username: postgres

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
